/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: any
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "link"?: string
    "category"?: string
    variant?: 'Desktop' | 'Tablet' | 'Phone' | 'Phone [Visible]' | 'Variant 5' | 'Phone [Dropdown]'
}

export declare const ChipFramerComponent: React.FC<Props>; 

export declare type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] };

export declare const ResponsiveChipFramerComponent: React.FC<Omit<Props, 'variant'> & { variants?: VariantsMap }>;

export default ChipFramerComponent

