// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 392f06e6dfe8d0e1 "BrightBites", do not edit manually */
"use client";
import {
  stdin_default
} from "./chunks/chunk-TJOR66J6.js";
import "./chunks/chunk-BTSBQWPZ.js";

// virtual:icon-buttons
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "J0kQyS61c",
  "sm": "S_fPV3l_2"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "Cvs0yr2VY": { "path": "/404" }, "WMZZJiNIc": { "path": "/contact" }, "XHgatBLBl": { "path": "/summaries/:slug/working" }, "augiA20Il": { "path": "/" }, "fZmAFZhNM": { "path": "/about" }, "hepRFlx9S": { "path": "/working_deprecated" }, "lMZ3Pz1wS": { "path": "/summaries/:slug/improvements" }, "qiA3JHonw": { "path": "/summaries/:slug" }, "usPwnQg05": { "path": "/summaries/:slug/not-working" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "392f06e6dfe8d0e1bc6936c1a53ce98f1691b0a6f0579b344145c0385aba2ecb",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "Cvs0yr2VY": {
          "path": "/404"
        },
        "WMZZJiNIc": {
          "path": "/contact"
        },
        "XHgatBLBl": {
          "path": "/summaries/:slug/working"
        },
        "augiA20Il": {
          "path": "/"
        },
        "fZmAFZhNM": {
          "path": "/about"
        },
        "hepRFlx9S": {
          "path": "/working_deprecated"
        },
        "lMZ3Pz1wS": {
          "path": "/summaries/:slug/improvements"
        },
        "qiA3JHonw": {
          "path": "/summaries/:slug"
        },
        "usPwnQg05": {
          "path": "/summaries/:slug/not-working"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "392f06e6dfe8d0e1bc6936c1a53ce98f1691b0a6f0579b344145c0385aba2ecb",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
