/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: '$spacing-10' | '$spacing-200' | '$spacing-100' | '$spacing-90' | '$spacing-80' | '$spacing-70' | '$spacing-60' | '$spacing-50' | '$spacing-40' | '$spacing-30' | '$spacing-25' | '$spacing-20' | '$spacing-15' | '$spacing-5'
}

const SpacingFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

SpacingFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default SpacingFramerComponent

