/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Horizontal' | 'Vertical' | 'Horizontal simple' | 'Vertical simple'
    "link"?: string
    "image"?: {src: string, srcSet?: string, alt?: string}
    "websiteName"?: string
    "description"?: string
    "category"?: string
    "authorPhoto"?: {src: string, srcSet?: string, alt?: string}
}

const CardFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

CardFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default CardFramerComponent

